#Build UI

FROM node:18 AS build
WORKDIR /app/ui
COPY ui/ .
RUN npm run install && npm run build


#Build backend

FROM node:18
WORKDIR /app/server
COPY server/ .
COPY --from=build /app/ui/dist ./public
RUN npm install

EXPOSE 7000
CMD [ "node", "server.js" ]
